### ISSUE TITLE
app should persist the last selected category

### ISSUE THREAD

**Issue by amwebexpert** [amwebexpert/guess_the_text#40]
Actual behavior:
- one categories are retrieved from API call, the app default selection to the very first one

Expected behavior:
- each time a user pick a category, we should persist the selected one
- on app startup we should check if we have a persisted category, double check if it (still) exists and select it

**Comment by JefvdA** [comment]
Hey,

I'll work on this issue if that's fine.

**Comment by amwebexpert** [comment]
Great!
