### ISSUE TITLE
list of authors and their website in about screen

### ISSUE THREAD

**Issue by amwebexpert** [amwebexpert/guess_the_text#51]
The project is having more than one contributor so improve the about screen accordingly by transforming the single author name and linkedin profile with a list of authors
- create the `Contributor` model class
- add a public array of hard coded contributors
- modify the `app.version.table.widget.dart` widget to iterate through the new contributors array and show their info

**Comment by JefvdA** [comment]
Hey, It's been a while and I'd like to contribute to the project again, so I'd like to do this issue. :)

Who are all the contributers I should add?

**Comment by amwebexpert** [comment]
> Hey, It's been a while and I'd like to contribute to the project again, so I'd like to do this issue. :)
> 
> Who are all the contributers I should add?

For now, you and I are the only real contributors, so just add both of us!
